# Generated by Django 3.2.6 on 2021-08-25 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=60, unique=True, verbose_name='Username')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Full Name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Created On')),
                ('profile', models.ImageField(default='profile1.png', upload_to='profiles/%Y/<django.db.models.fields.CharField>', verbose_name='Picture')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='Last login')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GoCustomerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Full name')),
                ('type', models.CharField(max_length=20, verbose_name='Customer Type')),
                ('destination', models.CharField(max_length=30, verbose_name='Destination')),
                ('time_of_submission', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(verbose_name='Age')),
                ('photo', models.ImageField(default='profile1.png', max_length=10000, upload_to='customers/profiles/', verbose_name='Customer Picture')),
                ('documents', models.FileField(default=None, max_length=1000, upload_to='customers/files/%Y/%m/%d', verbose_name='Documents')),
                ('registered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time_of_submission'],
            },
        ),
    ]
