# Generated by Django 3.2.6 on 2021-08-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='customers/profiles/')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.gocustomerregistration')),
            ],
        ),
    ]
